apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: winmorre/udagram-api-user:v3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "8240Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-properties
            - secretRef:
                name: app-secret
            - secretRef:
                name: aws-secret